---
# --> (Example) Create an IngressRoute for your service...
 apiVersion: traefik.io/v1alpha1
 kind: IngressRoute
 metadata:
   name: ceph-ingressroute-gui  # <-- Replace with your IngressRoute name
   namespace: rook-ceph  # <-- Replace with your namespace
 spec:
   entryPoints:
     - web
     - websecure
   routes:
     - match: Host(`ceph-dashboard.nerdy-apps-prod.jjland.local`)  # <-- Replace with your FQDN
       kind: Rule
       services:
         - name: rook-ceph-mgr-dashboard  # <-- Replace with your service name
           port: 7000
# --> (Optional) Add certificate secret
# tls:
#     secretName: your-certificate-secret
# <--
