grafana:
  
  # # To make Grafana persistent (Using Statefulset)
  # #
  persistence:
    enabled: true
    type: sts
    storageClassName: "rook-cephfs-delete"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
