repositories:
  - url: "https://github.com/leothelyon17/kubernetes-gitops-playground.git"
    type: git
    name: "GitOps Playground"
    project: "home-lab"
    username: ""
    password: ""
    oci_enabled: false
#  - url: "https://github.com/leothelyon17/kubernetes-gitops-playground.git"
#    type: git

    
