apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: heimdall-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-cephfs-retain
  resources:
    requests:
      storage: 1Gi
