apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-mistral-dev-cache
  namespace: ollama-mistral-dev
  labels:
    app: ollama-mistral
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "rook-cephfs-c-delete"
