apiVersion: v1
kind: Service
metadata:
  name: redis-memory
  namespace: ollama-mistral-dev
  labels:
    app: redis-memory
spec:
  type: ClusterIP
  selector:
    app: redis-memory
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
