apiVersion: v1
kind: Service
metadata:
  name: ollama-mistral-service
  namespace: ollama-mistral-dev
  labels:
    app: ollama-mistral
spec:
  selector:
    app: ollama-mistral
  ports:
    - name: http
      port: 11434
      targetPort: 11434
  type: ClusterIP
