apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wekan-mongodb-pvc
  namespace: wekan-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-retain
