apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-system
  namespace: argocd
spec:
  project: ahead-labs
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.11.0
    chart: external-secrets
  destination:
    server: https://lib-nautobot-04.lab.aheadaviation.com:6443
    namespace: external-secrets-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
