all:
  hosts:
    rocky9-lab-node1:
      ansible_host: 172.16.99.25
      ip: 172.16.99.25
      access_ip: 172.16.99.25
    rocky9-lab-node2:
      ansible_host: 172.16.99.26
      ip: 172.16.99.26
      access_ip: 172.16.99.26
    rocky9-lab-node3:
      ansible_host: 172.16.99.27
      ip: 172.16.99.27
      access_ip: 172.16.99.27
      
  children:
    kube_control_plane:
      hosts:
        rocky9-lab-node1:
            
    kube_node:
      hosts:
        rocky9-lab-node1:
        rocky9-lab-node2:
        rocky9-lab-node3:
            
    etcd:
      hosts:
        rocky9-lab-node1:
            
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr: 
      hosts: {}
