global:
  clusterDomain: jjland.local
  clusterName: prod-cluster

clickhouse:
  zookeeper:
    persistence:
      storageClass: rook-cephfs-retain
      size: 5Gi
  persistence:
    storageClass: rook-cephfs-retain
    size: 10Gi

signoz:
  persistence:
    storageClass: rook-cephfs-retain
    size: 2Gi
