---
apiVersion: v1
kind: ConfigMap
metadata:
    name: spine-leaf-borderleaf-node-1-startup-config
    namespace: c9s-load-balancer-test
data:
  startup-config: |-
    !
    daemon TerminAttr
       exec /usr/bin/TerminAttr -cvaddr=172.18.100.99:9910 -cvauth=token,/tmp/token -cvvrf=MGMT -disableaaa -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs
       no shutdown
    !
    hostname dc1-spine1
    !
    ! 
    username ansible privilege 15 role network-admin secret 0 lab123
    !
    ! 
    vrf instance MGMT
    !
    !
    interface Management0
       description oob_management
       no shutdown
       vrf MGMT
       ! IP address - must be set uniquely per device
       ip address 192.168.101.170/29
    !
    ip routing
    ip routing vrf MGMT
    !
    ip route vrf MGMT 0.0.0.0/0 192.168.101.169
    !
    !
    management api http-commands
       protocol https
       no shutdown
       !
       vrf MGMT
          no shutdown
    !
    end
    !
    !
    copy running-config startup-config
