{{- if .Values.portal.ingress.enabled -}}
{{- $fullName := include "slurpit.name" . -}}
{{- if and .Values.portal.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.portal.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.portal.ingress.annotations "kubernetes.io/ingress.class" .Values.portal.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "slurpit.labels" . | nindent 4 }}
  {{- if or .Values.portal.commonAnnotations .Values.portal.ingress.annotations }}
  annotations:
  {{- with .Values.portal.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.portal.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if and .Values.portal.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.portal.ingress.className }}
  {{- end }}
  {{- if .Values.portal.ingress.tls }}
  tls:
    {{- range .Values.portal.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.portal.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- if kindIs "string" . }}
          - path: {{ . }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-portal-service
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: http
              {{- end }}
          {{- else }}
          - {{ . | toYaml | indent 12 | trim }}
          {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
