apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurpit.name" . }}-portal-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "slurpit.name" . }}-portal-app
  type: {{ .Values.portal.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.portal.service.port }}
      name: http
      targetPort: {{ .Values.portal.ports.containerPort }}
      {{- if eq $.Values.portal.service.type "NodePort" }}
      nodePort: {{ .Values.portal.service.nodePort }}
      {{ end }}
