all:
  hosts:
    rocky9-prod-node1:
      ansible_host: 192.168.101.157
      ip: 192.168.101.157
      access_ip: 192.168.101.157
    rocky9-prod-node2:
      ansible_host: 192.168.101.158
      ip: 192.168.101.158
      access_ip: 192.168.101.158
    rocky9-prod-node3:
      ansible_host: 192.168.101.159
      ip: 192.168.101.159
      access_ip: 192.168.101.159
      
  children:
    kube_control_plane:
      hosts:
        rocky9-prod-node1:
        rocky9-prod-node2:
        rocky9-prod-node3:
            
    kube_node:
      hosts:
        rocky9-prod-node1:
        rocky9-prod-node2:
        rocky9-prod-node3:
            
    etcd:
      hosts:
        rocky9-prod-node1:
        rocky9-prod-node2:
        rocky9-prod-node3:
            
    k8s_cluster:
      vars:
        supplementary_addresses_in_ssl_keys: ['prod-cluster.jjland.local']
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
