apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: github-exporter-servicemonitor
  labels:
    release: kube-prometheus-stack
  namespace: monitoring-prod
spec:
  selector:
    matchLabels:
      app: github-exporter
  endpoints:
  - port: http
    interval: 60s
