apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: c9s-spine-leaf-borderleaf
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend        # Your pre-configured Vault SecretStore name
    kind: ClusterSecretStore
  target:
    name: ghcr-secret    # Name of the secret to be created in Kubernetes
    template:
      type: Opaque
      data:
        config.json: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ .data.base64 }}",
                "email": "{{ .data.email }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: "secret/data/my-github"   # Adjust if your Vault KV engine uses a different path (e.g., KV v2)
        property: username
    - secretKey: pat
      remoteRef:
        key: "secret/data/my-github"
        property: pat
    - secretKey: email
      remoteRef:
        key: "secret/data/my-github"
        property: email
    - secretKey: base64
      remoteRef:
        key: "secret/data/my-github"
        property: base64
