apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-llama32-dev-cache
  namespace: ollama-llama32-dev
  labels:
    app: ollama-llama32
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "rook-cephfs-c-delete"
