apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-memory-pvc
  namespace: ollama-llama32-dev
  labels:
    app: redis-memory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-c-delete
