apiVersion: v1
kind: Service
metadata:
  name: ollama-llama32-service
  namespace: ollama-llama32-dev
  labels:
    app: ollama-llama32
spec:
  selector:
    app: ollama-llama32
  ports:
    - name: http
      port: 11434
      targetPort: 11434
  type: ClusterIP
