---
# --> (Example) Create an IngressRoute for your service...
 apiVersion: traefik.io/v1alpha1
 kind: IngressRoute
 metadata:
   name: slurpit-lab-ingressroute  # <-- Replace with your IngressRoute name
   namespace: slurpit-lab  # <-- Replace with your namespace
 spec:
   entryPoints:
     - web
     - websecure
   routes:
     - match: Host(`slurpit.nerdy-apps-lab.jjland.local`)  # <-- Replace with your FQDN
       kind: Rule
       services:
         - name: slurpit-portal-service  # <-- Replace with your service name
           port: 80
# --> (Optional) Add certificate secret
# tls:
#     secretName: your-certificate-secret
# <--
