apiVersion: v1
kind: Namespace
metadata:
  name: vllm-gpt-oss-20b-dev
  labels:
    app.kubernetes.io/name: vllm-gpt-oss-20b
    app.kubernetes.io/part-of: vllm
    app.kubernetes.io/component: inference
