apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nautobot-prod-superuser-external-secret
  namespace: nautobot-prod
spec:
  refreshInterval: "1h" # Refresh every hour
  secretStoreRef:
    name: vault-backend             # Name of the SecretStore resource
    kind: ClusterSecretStore                # SecretStore or ClusterSecretStore
  target:
    name: nautobot-prod-superuser-secrets           # Name of the Kubernetes secret to create
    creationPolicy: Owner            # Replace or update the secret
  
  data:

    - secretKey: password      # Key for Netbox Superuser password
      remoteRef:
        key: secret/data/nautobot-prod-superuser-credentials
        property: superuser-pass

    - secretKey: api_token     # Key for Netbox Superuser password
      remoteRef:
        key: secret/data/nautobot-prod-superuser-credentials
        property: superuser-api-token
