apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-credentials-secret
  namespace: nautobot-prod
spec:
  refreshInterval: "1h"  # How often to sync the secret
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: net-automation-k8s-repo-credentials  # Name of the Kubernetes Secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .dockerserver }}": {
                "username": "{{ .dockerusername }}",
                "password": "{{ .dockerpassword }}",
                "email": "{{ .dockeremail }}"
              }
            }
          }
  data:
    - secretKey: dockerusername
      remoteRef:
        key: secret/my-github
        property: username
    - secretKey: dockerpassword
      remoteRef:
        key: secret/my-github
        property: pat
    - secretKey: dockeremail
      remoteRef:
        key: secret/my-github
        property: email
    - secretKey: dockerserver
      remoteRef:
        key: secret/my-github
        property: server
