entryPoints:
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - 192.168.0.0/16   # your LAN subnet (if Traefik receives traffic from these)
        - 10.0.0.0/8       # any other trusted proxy ranges
  plex:
    address: ":32400"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - 192.168.0.0/16

ingressRoute:
  dashboard:
    enabled: true
    # Custom match rule with host domain
    matchRule: Host(`traefik-dashboard-prod.jjland.local`)
    entryPoints: ["web", "websecure"]
    # Add custom middlewares : authentication and redirection
    middlewares:
      - name: traefik-dashboard-auth

# Create the custom middlewares used by the IngressRoute dashboard (can also be created in another way).
# /!\ Yes, you need to replace "changeme" password with a better one. /!\
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: changeme

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret

service:
  spec:
    loadBalancerIP: 192.168.101.161
