---
# --> (Example) Create an IngressRoute for your service...
 apiVersion: traefik.io/v1alpha1
 kind: IngressRoute
 metadata:
   name: overseerr-app-ingressroute  # <-- Replace with your IngressRoute name
   namespace: overseerr-app-prod  # <-- Replace with your namespace
 spec:
   entryPoints:
     - websecure
   routes:
     - match: Host(`overseerr.nerdylyonsden.io`)  # <-- Replace with your FQDN
       kind: Rule
       services:
         - name: overseerr-app-prod  # <-- Replace with your service name
           port: 5055
   tls:
     secretName: prod-apps-certificate-secret
