rrdcached:
    persistence:
      # -- RRDCached persistent volume enabled
      enabled: true
      storageClass: "rook-cephfs"
      journal:
        # -- RRDCached journal PV size
        size: 1Gi
      rrdcached:
        # -- RRDCached RRD storage PV size
        size: 2Gi
mysql:
  primary:
    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "rook-cephfs"
      accessModes: ['ReadWriteOnce']
redis:
  master:
    persistence:
      enabled: true
      size: "1Gi"
      storageClass: "rook-cephfs"
      accessModes: ['ReadWriteOnce']
