apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-prod-secrets
  namespace: netbox-prod
spec:
  refreshInterval: "1h" # Refresh every hour
  secretStoreRef:
    name: vault-backend-netbox-prod              # Name of the SecretStore resource
    kind: ClusterSecretStore                # SecretStore or ClusterSecretStore
  target:
    name: netbox-prod-secrets           # Name of the Kubernetes secret to create
    creationPolicy: Owner            # Replace or update the secret
  data:
    - secretKey: postgres-password       # Key for Postgres 'postgres' user in the K8s secret
      remoteRef:
        key: secret/data/netbox-prod-credentials    # Path in Vault (adjust based on your setup)
        property: postgres-pass      # Key in the Vault secret

    - secretKey: password   # Key for Postgres password in the K8s secret
      remoteRef:
        key: secret/data/netbox-prod-credentials
        property: postgres-pass

    - secretKey: redis-password      # Key for Redis password
      remoteRef:
        key: secret/data/netbox-prod-credentials
        property: redis-pass

    - secretKey: dockerusername
      remoteRef:
        key: secret/data/net-automation-repo-credentials
        property: dockerusername
    
    - secretKey: dockerpassword
      remoteRef:
        key: secret/data/net-automation-repo-credentials
        property: dockerpassword
