apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-branching-cm
data:
  local_settings.py: |
    from netbox_branching.utilities import DynamicSchemaDict

    DATABASES = DynamicSchemaDict({
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'netbox',               # Database name
            'USER': 'netbox',               # PostgreSQL username
            'PASSWORD': 'password',         # PostgreSQL password
            'HOST': 'localhost',            # Database server
            'PORT': '',                     # Database port (leave blank for default)
            'CONN_MAX_AGE': 300,            # Max database connection age
        }
    })
    
    DATABASE_ROUTERS = [
        'netbox_branching.database.BranchAwareRouter',
    ]
