apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-inspector-prod-proxy-token
  namespace: mcp-inspector-prod
spec:
  refreshInterval: "1h" # Refresh every hour
  secretStoreRef:
    name: vault-backend-mcp-inspector-prod              # Name of the SecretStore resource
    kind: ClusterSecretStore                # SecretStore or ClusterSecretStore
  target:
    name: mcp-inspector-prod-proxy-token          # Name of the Kubernetes secret to create
    creationPolicy: Owner            # Replace or update the secret
  
  data:
    - secretKey: proxy-token
      remoteRef:
        key: secret/data/mcp-inspector
        property: proxy-token
