apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-prod
spec:
  secretName: prod-apps-certificate-secret
  commonName: "*.nerdylyonsden.io"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - "*.nerdylyonsden.io"
