apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-prod
spec:
  secretName: prod-apps-certificate-secret
  commonName: "*.nerdylyonsden.io"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - "*.nerdylyonsden.io"
  - "*.home.nerdylyonsden.io"

  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "nautobot-prod, rook-ceph, heimdall-prod, clabernetes-prod, hashi-vault-prod"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "nautobot-prod, rook-ceph, heimdall-prod, clabernetes-prod, hashi-vault-prod"
