image:
  registry: ghcr.io
  repository: ghcr.io/leothelyon17/kubernetes-gitops-playground/netbox/dev
  pullPolicy: Always
  tag: "latest"
  pullSecrets:
    - net-automation-k8s-repo-credentials

command:
  - /bin/bash
  - -c
  - |
    source /opt/netbox/venv/bin/activate && \
    python3 /opt/netbox/netbox/manage.py migrate && \
    python3 /opt/netbox/netbox/manage.py collectstatic --no-input && \
    python3 /opt/netbox/netbox/manage.py reindex && \
    /opt/netbox/docker-entrypoint.sh && \
    /opt/netbox/launch-netbox.sh

initContainers:
  - name: git-fetch
    image: alpine/git
    env:
      - name: GIT_USERNAME
        valueFrom:
          secretKeyRef:
            name: netbox-prod-secrets
            key: dockerusername
      - name: GIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: netbox-prod-secrets
            key: dockerpassword
            
    command:
      - /bin/sh
      - -c
      - |
        git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/leothelyon17/kubernetes-gitops-playground.git /tmp-netbox-prod && \
        cp -r /tmp-netbox-prod/apps/netbox/overlays/prod/configuration/* /shared-volume/
    volumeMounts:
      - name: shared-volume
        mountPath: /shared-volume

extraVolumes:
    - name: shared-volume
      emptyDir: {}
    - name: netbox-secrets-writable
      emptyDir: {}
    - name: netbox-branching-config
      configMap:
        name: netbox-branching-cm

extraVolumeMounts:
    - name: shared-volume
      mountPath: /etc/netbox/config/
    - name: netbox-secrets-writable
      mountPath: /opt/netbox/netbox/static/netbox_secrets/
    - name: netbox-branching-config
      mountPath: /opt/netbox/netbox/netbox/local_settings.py
      subPath: local_settings.py

startupProbe:
  enabled: false
  initialDelaySeconds: 25
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 30
  successThreshold: 1
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

clusterDomain: jjland.local

extraEnvVarsSecret: netbox-prod-secrets

superuser:
  existingSecret: netbox-prod-superuser-secrets

persistence:
  enabled: true
  storageClass: "rook-cephfs-delete"
  accessMode: ReadWriteMany
  size: 1Gi

postgresql:
  primary:
    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "rook-cephfs-retain"
      accessModes: ['ReadWriteOnce']
  auth:
    existingSecret: netbox-prod-secrets
  
  initdbScripts:
    grant-create.sql: |
      GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};

valkey:
  primary:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
    persistence:
      enabled: false
    

# redis:
#   architecture: "standalone"
#   master:
#     persistence:
#       enabled: true
#       size: "1Gi"
#       storageClass: "rook-cephfs-delete"
#       accessModes: ['ReadWriteOnce']
#   auth:
#     enabled: true
#     existingSecret: netbox-prod-secrets
