clusterDomain: jjland.local

persistence:
  enabled: true
  storageClass: "rook-cephfs"
  accessMode: ReadWriteMany
  size: 1Gi

postgresql:
  primary:
    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "rook-cephfs"
      accessModes: ['ReadWriteOnce']

redis:
  architecture: "standalone"
  master:
    persistence:
      enabled: true
      size: "1Gi"
      storageClass: "rook-cephfs"
      accessModes: ['ReadWriteOnce']
