apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-bge-base-en-v1-5-cache
  namespace: vllm-bge-base-en-v1-5-dev
  labels:
    app.kubernetes.io/name: vllm-bge-base-en-v1-5
    app.kubernetes.io/instance: bge-base-en-v1-5-dev
    app.kubernetes.io/component: inference
    app.kubernetes.io/part-of: vllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs-delete
