apiVersion: v1
kind: Service
metadata:
  name: vllm-bge-base-en-v1-5
  namespace: vllm-bge-base-en-v1-5-dev
  labels:
    app.kubernetes.io/name: vllm-bge-base-en-v1-5
    app.kubernetes.io/instance: bge-base-en-v1-5-dev
    app.kubernetes.io/component: inference
    app.kubernetes.io/part-of: vllm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vllm-bge-base-en-v1-5
    app.kubernetes.io/instance: bge-base-en-v1-5-dev
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
