apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wikijs-prod-secrets
  namespace: wikijs-prod
spec:
  refreshInterval: "1h" # Refresh every hour
  secretStoreRef:
    name: vault-backend-wikijs-prod              # Name of the SecretStore resource
    kind: ClusterSecretStore                # SecretStore or ClusterSecretStore
  target:
    name: wikijs-prod-secrets           # Name of the Kubernetes secret to create
    creationPolicy: Owner            # Replace or update the secret
  data:
    - secretKey: postgres-password       # Key for Postgres 'postgres' user in the K8s secret
      remoteRef:
        key: secret/data/wikijs    # Path in Vault (adjust based on your setup)
        property: postgres-pass      # Key in the Vault secret
