apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-rustfs-prod
  namespace: rustfs-prod
spec:
  provider:
    vault:
      server: "http://hashi-vault-prod-0.hashi-vault-prod-internal.hashi-vault-prod.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "rustfs"
          serviceAccountRef:
            name: rustfs-prod
            namespace: rustfs-prod
