apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-artifacts
  namespace: argo-workflows-prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-argo-workflows-prod
    kind: SecretStore
  target:
    name: argo-workflows-artifacts
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef:
        key: secret/data/rustfs-prod-credentials
        property: argo_workflows_access_key
    - secretKey: secretkey
      remoteRef:
        key: secret/data/rustfs-prod-credentials
        property: argo_workflows_secret_key
