apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-argo-workflows-prod
  namespace: argo-workflows-prod
spec:
  provider:
    vault:
      server: "http://hashi-vault-prod-0.hashi-vault-prod-internal.hashi-vault-prod.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argo-workflows"
          serviceAccountRef:
            name: argo-workflow
            namespace: argo-workflows-prod
