apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient
  namespace: ddclient-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      initContainers:
        - name: generate-config
          image: alpine:latest
          env:
            - name: DDCLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ddclient-secrets
                  key: ddclient_password
            - name: DDCLIENT_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: ddclient-secrets
                  key: ddclient_protocol
            - name: DDCLIENT_LOGIN
              valueFrom:
                secretKeyRef:
                  name: ddclient-secrets
                  key: ddclient_login
            - name: DDCLIENT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ddclient-secrets
                  key: ddclient_domain
          command: [ "sh", "-c", "apk add --no-cache gettext && envsubst < /config-template/ddclient.conf.template > /config/ddclient/ddclient.conf" ]
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config
              mountPath: /config/ddclient
      containers:
        - name: ddclient
          image: linuxserver/ddclient:latest
          # The image expects its configuration at /config/ddclient/ddclient.conf
          volumeMounts:
            - name: config
              mountPath: /config/ddclient
          env:
            - name: TZ
              value: "EST"
      volumes:
        - name: config-template
          configMap:
            name: ddclient-config-template
        - name: config
          emptyDir: {}
