apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddclient-secret
  namespace: ddclient-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ddclient-secrets
    creationPolicy: Owner
  data:
    - secretKey: ddclient_password
      remoteRef:
        key: /path/to/ddclient-credentials/password
    - secretKey: ddclient_login
      remoteRef:
        key: /path/to/ddclient-credentials/login
    - secretKey: ddclient_domain
      remoteRef:
        key: /path/to/ddclient-credentials/domain
    - secretKey: ddclient_protocol
      remoteRef:
        key: /path/to/ddclient-credentials/protocol
