apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prod-traefik-pool
  namespace: metallb-prod
spec:
  addresses:
  - 192.168.101.161/32    # Traefik IP
  - 192.168.101.224/28    # Clabernetes Pool
