apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-unbound-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.104.18-192.168.104.18   # or a small range you reserve
