apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-prod
  namespace: argocd
spec:
  project: prod-home
source:
  repoURL: https://charts.external-secrets.io
  targetRevision: 0.14.1
  helm:
    parameters:
      - name: certController.image.repository
        value: ghcr.io/external-secrets/external-secrets
      - name: image.repository
        value: ghcr.io/external-secrets/external-secrets
      - name: webhook.image.repository
        value: ghcr.io/external-secrets/external-secrets
  chart: external-secrets
destination:
  server: https://prod-kube-vip.jjland.local:6443
  namespace: external-secrets-prod
syncPolicy:
  syncOptions:
    - CreateNamespace=true
