apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  project: prod-home
destination:
  server: https://prod-kube-vip.jjland.local:6443
  namespace: kube-vip
syncPolicy:
  syncOptions:
    - CreateNamespace=true
sources:
  - repoURL: https://kube-vip.github.io/helm-charts/
    targetRevision: 0.6.6
    helm:
      valueFiles:
        - $values/apps/kube-vip/values-prod.yml
    chart: kube-vip
  - repoURL: https://github.com/leothelyon17/kubernetes-gitops-playground.git
    targetRevision: HEAD
    ref: values
