apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nerdy-k8s-volume-manager-prod
  namespace: argocd
spec:
  project: prod-home
  destination:
    server: https://prod-kube-vip.jjland.local:6443
    namespace: nerdy-k8s-volume-manager-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/leothelyon17/kubernetes-gitops-playground.git
      path: apps/nerdy-k8s-volume-manager/overlays/prod
      targetRevision: HEAD
