apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nautobot-db-secrets
  namespace: nautobot-lab
spec:
  refreshInterval: "1h" # Refresh every hour
  secretStoreRef:
    name: vault-backend              # Name of the SecretStore resource
    kind: ClusterSecretStore                # SecretStore or ClusterSecretStore
  target:
    name: nautobot-test-secrets           # Name of the Kubernetes secret to create
    creationPolicy: Owner            # Replace or update the secret
  data:
    - secretKey: postgres-password       # Key for Postgres 'postgres' user in the K8s secret
      remoteRef:
        key: secret/data/nautobot-db-credentials    # Path in Vault (adjust based on your setup)
        property: postgres-pass      # Key in the Vault secret

    - secretKey: password   # Key for Postgres password in the K8s secret
      remoteRef:
        key: secret/data/nautobot-db-credentials
        property: postgres-pass

    - secretKey: redis-password      # Key for Redis password
      remoteRef:
        key: secret/data/nautobot-db-credentials
        property: redis-pass
