nautobot:

  command:
    - /bin/sh
    - -c
    - |
      cp /tmp/nautobot_config.py /opt/nautobot/nautobot_config.py && \
      nautobot-server post_upgrade && \
      nautobot-server start --ini /opt/nautobot/uwsgi.ini

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

  initContainers:
    - name: git-fetch
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          git clone https://github.com/leothelyon17/kubernetes-gitops-playground.git /tmp \
          && cp /tmp/apps/nautobot/overlays/prod/configuration/nautobot_config.py /shared-volume/
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-volume

  extraVolumes:
    - name: shared-volume
      emptyDir: {}

  extraVolumeMounts:
    - name: shared-volume
      mountPath: /tmp

  superUser:
      existingSecret: "nautobot-prod-superuser-secrets"
      existingSecretPasswordKey: "password"
      existingSecretApiTokenKey: "api_token"
      username: "jeff"
  

postgresql:
  primary:
    persistence:
      enabled: true
      size: "2Gi"
      storageClass: "rook-cephfsretain"
      accessModes: ['ReadWriteOnce']
  auth:
    existingSecret: nautobot-dev-secrets

redis:
  master:
    persistence:
      enabled: true
      size: "1Gi"
      storageClass: "rook-cephfs-delete"
      accessModes: ['ReadWriteOnce']
  auth:
    enabled: true
    existingSecret: nautobot-dev-secrets
