nautobot:
  extraEnvVarsSecret: ["nautobot-test-secrets"]
#   db:
#     # -- Name of existing secret to use for Database passwords<sup>[1](#notes)</sup>
#     existingSecret: "nautobot-test-secrets"
#     # -- Password key to be retrieved from existing secret<sup>[1](#notes)</sup>
#     existingSecretPasswordKey: "password"
  
#   redis:
#     # -- Name of existing secret to use for Redis passwords<sup>[1](#notes)</sup>
#     existingSecret: "nautobot-test-secrets"
#     # -- Password key to be retrieved from existing secret<sup>[1](#notes)</sup>
#     existingSecretPasswordKey: "redis-password"

postgresql:
  primary:
    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "rook-cephfs"
      accessModes: ['ReadWriteOnce']
  auth:
    #password: "nautobot-postgres-pass"
    existingSecret: nautobot-test-secrets
    #usernameKey: POSTGRES_USER
    #passwordKey: POSTGRES_PASSWORD

redis:
  master:
    persistence:
      enabled: true
      size: "1Gi"
      storageClass: "rook-cephfs"
      accessModes: ['ReadWriteOnce']
  auth:
    enabled: true
    existingSecret: nautobot-test-secrets
    #usernameKey: REDIS_USER
    #passwordKey: REDIS_PASSWORD
    #password: "nautobot-redis-pass"
