apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nkvm-cluster-discovery-prod
  labels:
    app.kubernetes.io/name: nerdy-k8s-volume-manager
    app.kubernetes.io/instance: nerdy-k8s-volume-manager-prod
    app.kubernetes.io/component: discovery
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get"]
