apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-namecheap
  namespace: traefik-prod
spec:
  acme:
    email: your-email@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-namecheap-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.namecheap.webhook
            solverName: namecheap
            config:
              usernameSecretRef:
                name: cert-manager-prod-secrets
                key: api-user
              apiKeySecretRef:
                name: cert-manager-prod-secrets
                key: api-token
                  
