apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nautobot-prod-cert
  #namespace: traefik-prod
spec:
  secretName: nautobot-prod-cert-secret
  issuerRef:
    name: letsencrypt-namecheap
    kind: ClusterIssuer
  dnsNames:
    - nautobot.nerdylyonsden.io
