name: Install ArgoCD and CLI

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
        environment:
          description: "The environment to deploy to"
          required: true
          default: "lab"
          type: choice
          options:
            - lab
            - prod

env:
  ARGOCD_PORT: ${{ vars.ARGOCD_PORT }}
  ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
  ARGOCD_PASSWORD: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
  ARGOCD_USERNAME: ${{ secrets.ARGOCD_ADMIN_USER }}
  ADMIN_USERNAME: ${{ secrets.ARGOCD_MY_ADMIN_USER }}
  ADMIN_PASSWORD: ${{ secrets.ARGOCD_MY_ADMIN_PASSWORD }}

jobs:
  # set-environment:
  #   runs-on: self-hosted
  #   outputs:
  #     ENV_NAME: ${{ steps.detect_env.outputs.env_name }}
  #   steps:
  #   - name: Determine Environment
  #     id: detect_env
  #     run: |
  #       if git diff --name-only HEAD~1 | grep '^lab/'; then
  #         echo "env_name=lab" >> $GITHUB_OUTPUT
  #       elif git diff --name-only HEAD~1 | grep '^prod/'; then
  #         echo "env_name=prod" >> $GITHUB_OUTPUT
  #       else
  #         echo "env_name=lab" >> $GITHUB_OUTPUT
  #       fi
  
  install-argocd:
    #needs: set-environment
    environment: ${{ github.event.inputs.environment }}
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Environment Name Variable Dynamically
      id: set-environment-variable
      run: echo "ENV_NAME=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

    # Set Correct Kubernetes Context
    - name: Set Correct Kubernetes Context
      run: |
        kubectl config use-context "${{ env.ENV_NAME }}-kubernetes-admin@${{ env.ENV_NAME }}-cluster.jjland.local"

    # Install Argo CD
    - name: Install Argo CD on Kubernetes
      run: |
        kubectl create namespace argocd || true
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    # Install Argo CD CLI
    - name: Install Argo CD CLI
      run: |
        sudo rm -rf argocd
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/

    # Wait for Argo CD Server to be Ready
    - name: Wait for Argo CD components
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd

    # Expose Argo CD Server (Optional)
    - name: Expose Argo CD Server
      run: |
        kubectl patch svc argocd-server -n argocd \
          -p '{"spec": {"type": "NodePort", "ports": [{"port": 443, "targetPort": 8080, "nodePort": '"$ARGOCD_PORT"' }]}}'

    # Log in to ArgoCD
    - name: Login to ArgoCD
      run: |
        argocd login $ARGOCD_SERVER:$ARGOCD_PORT \
          --username $ARGOCD_USERNAME \
          --password $ARGOCD_PASSWORD \
          --insecure

    # Create Additional Admin User ConfigMap
    - name: Create Admin User ConfigMap
      run: |
        kubectl get configmap argocd-cm -n argocd -o yaml > argocd-cm.yaml

        # Add new admin user for login
        echo "
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: argocd-cm
          namespace: argocd
          labels:
            app.kubernetes.io/name: argocd-cm
            app.kubernetes.io/part-of: argocd
        data:
          accounts.$ADMIN_USERNAME: login
        " > argocd-cm.yaml

        # Apply configmap
        kubectl -n argocd apply -f argocd-cm.yaml

    # Create Additional Admin User RBAC
    - name: Create Admin User RBAC
      run: |
        kubectl -n argocd get configmap argocd-rbac-cm -o yaml > rbac-config.yaml

        # Add new admin user and role
        echo "
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: argocd-rbac-cm
          namespace: argocd
          labels:
            app.kubernetes.io/name: argocd-rbac-cm
            app.kubernetes.io/part-of: argocd
        data:
          policy.csv: |
            p, role:admin, applications, *, *, allow
            g, $ADMIN_USERNAME, role:admin
        " > rbac-config.yaml

        # Apply RBAC configmap
        kubectl config get-contexts
        kubectl -n argocd apply -f rbac-config.yaml

        # Add the admin user
        argocd account update-password --account $ADMIN_USERNAME --current-password ${{ secrets.ARGOCD_ADMIN_PASSWORD }} --new-password $ADMIN_PASSWORD

        echo "Admin user $ADMIN_USERNAME created successfully."

    # Verify Admin User Creation
    - name: Verify Admin User
      run: |
        echo "Attempting to log in with the new admin user..."
        argocd login $ARGOCD_SERVER:$ARGOCD_PORT \
          --username ${{ secrets.ARGOCD_MY_ADMIN_USER }} \
          --password ${{ secrets.ARGOCD_MY_ADMIN_PASSWORD }} \
          --insecure
        echo "New admin user login successful."

    # Add the cluster to ArgoCD if not exists
    - name: Add Cluster to ArgoCD
      run: |
        CLUSTER_NAME=$ENV_NAME-cluster
        CONTEXT=$(kubectl config current-context)
        EXISTS=$(argocd cluster get $CLUSTER_NAME || echo "not found")
        if [[ "$EXISTS" == "not found" ]]; then
          echo "Cluster $CLUSTER_NAME not found. Adding it..."
          argocd cluster add $CONTEXT --name $CLUSTER_NAME --yes
        else
          echo "Cluster $CLUSTER_NAME already exists."
        fi
