name: Setup and Test Kubernetes Access

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  install-kubectl:
    runs-on: self-hosted

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install kubectl if not present
    - name: Install kubectl
      run: |
        if ! command -v kubectl &> /dev/null; then
          echo "kubectl not found, installing..."
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
        else
          echo "kubectl already installed."
        fi
        kubectl version --client
    
  create-kube-configs:
    runs-on: self-hosted

    strategy:
      matrix:
        environment: ["lab", "prod"]
      fail-fast: false

    environment: ${{ matrix.environment }}

    steps:

    - name: Combine and decode kubeconfigs
      env:
        ENVIRONMENT: ${{ matrix.environment }}
      run: |
        kubeconfig_path="$HOME/.kube/${{ matrix.environment }}-kubeconfig.yaml"
        
        echo "Processing environment: $ENVIRONMENT"

        # Check if the secret exists
        if [[ -n "${{ secrets.KUBECONFIG_BASE64 }}" ]]; then
          echo "Found KUBECONFIG_BASE64 secret for $ENVIRONMENT"

          # Decode the secret and save it as a kubeconfig file
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > "$kubeconfig_path"
          echo "Kubeconfig for $ENVIRONMENT saved at $kubeconfig_path"
        else
          echo "No KUBECONFIG_BASE64 secret found for $ENVIRONMENT"
        fi
    
  flatten-and-test:
    runs-on: self-hosted

    steps:
    - name: Set up directories
      run: |
        mkdir -p $HOME/.kube
        echo "Kube config directory created at $HOME/.kube"
    
    - name: Combine all kube configs into a single file
      run: |
        combined_config="$HOME/.kube/config"
        echo "Combining kube configs into $combined_config"
        
        # Initialize combined config
        touch "$combined_config"
    
        # Combine kube configs
        kubeconfigs=""
        for config_file in $HOME/.kube/*-kubeconfig.yaml; do
          if [[ -f "$config_file" ]]; then
            echo "Adding $config_file to combined config"
            kubeconfigs="$kubeconfigs:$config_file"
          else
            echo "No kube config files found in $HOME/.kube/"
          fi
        done
    
        # Remove leading colon from the KUBECONFIG string
        kubeconfigs="${kubeconfigs#:}"
    
        # Set KUBECONFIG and flatten the config files into a single combined config
        if [[ -n "$kubeconfigs" ]]; then
          KUBECONFIG="$kubeconfigs" kubectl config view --flatten > "$combined_config"
          chmod 600 "$combined_config"
          echo "Combined kube config saved at $combined_config"
        else
          echo "No kube config files were found to combine."
        fi
    
    - name: Verify Kube config
      run: |
        kubectl config get-contexts
        kubectl version
        kubectl get nodes
