name: Install Python 3.12 on Rocky Linux 9

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-python:
    runs-on: self-hosted
    steps:
      - name: Check for Python 3.12
        run: |
          if ! python3.12 --version; then
            echo "Python 3.12 not found. Proceeding with installation."
          else
            echo "Python 3.12 is already installed."
          fi

      - name: Install dependencies
        run: |
          sudo dnf -y groupinstall "Development Tools"
          sudo dnf -y install gcc gcc-c++ make zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl openssl-devel libffi libffi-devel xz-devel

      - name: Download and install Python 3.12
        run: |
          cd /usr/src
          sudo curl -O https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
          sudo tar xzf Python-3.12.0.tgz
          cd Python-3.12.0
          sudo ./configure --enable-optimizations
          sudo make altinstall
          sudo ln -sf /usr/local/bin/python3.12 /usr/bin/python3.12

      - name: Verify Python installation
        run: |
          python3.12 --version
          pip3.12 --version
