name: Install Tools on Rocky Linux 9 runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-python:
    runs-on: self-hosted
    steps:
      - name: Check for Python 3.12
        run: |
          if ! python3.12 --version; then
            echo "Python 3.12 not found. Proceeding with installation."
            sudo dnf -y groupinstall "Development Tools"
            sudo dnf -y install gcc gcc-c++ make zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl openssl-devel libffi libffi-devel xz-devel
            cd /usr/src
            sudo curl -O https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
            sudo tar xzf Python-3.12.0.tgz
            cd Python-3.12.0
            sudo ./configure --enable-optimizations
            sudo make altinstall
            sudo ln -sf /usr/local/bin/python3.12 /usr/bin/python3.12
          else
            echo "Python 3.12 is already installed."
          fi
      
      - name: Verify Python installation
        run: |
          python3.12 --version
          pip3.12 --version

  install-docker:
    runs-on: self-hosted
    steps:
      - name: Check if Docker is installed
        id: check-docker
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed"
            echo "needs_install=true" >> $GITHUB_ENV
          else
            echo "Docker is already installed"
            echo "needs_install=false" >> $GITHUB_ENV
          fi

      - name: Install Docker
        if: env.needs_install == 'true'
        run: |
          sudo dnf -y install dnf-plugins-core
          sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo systemctl enable --now docker
          sudo usermod -aG docker $USER

      - name: Verify Docker Installation
        run: |
          docker --version
          sudo systemctl status docker
